version: "3"
services:
  postgres-server:
    image: postgres:latest
    env_file:
      - ./envForCompose/.postgres-env

  node-server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 4000:4000
    depends_on:
      - postgres-server
